module.exports = {
  "prefer-const": [
    "error",
    {
      destructuring: "all",
      ignoreReadBeforeAssign: true,
    },
  ],
  "no-console": ["error", { allow: ["warn", "error"] }],
  eqeqeq: ["error", "always"],
  "no-magic-numbers": [
    "error",
    { ignoreArrayIndexes: true, ignoreDefaultValues: true },
  ],
  "no-param-reassign": "error",
  "prefer-arrow-callback": "error",
  "prefer-destructuring": ["error", { object: true }],
  "prefer-object-spread": "error",
  "no-var": "error",
  "prefer-template": "error",
  "max-params": ["error", { max: 3 }],
  "consistent-return": ["error", { treatUndefinedAsUnspecified: true }],
  "no-useless-return": "warn",
  "no-throw-literal": "error",
  "no-nested-ternary": "error",
  "no-unneeded-ternary": "error",
  "default-case": "error",
  "default-case-last": "error",
  "max-depth": ["error", { max: 3 }],
  "one-var": ["error", "never"],
  "no-useless-computed-key": "error",
  "no-duplicate-imports": "error",
  "no-use-before-define": "error",
  complexity: ["error", { max: 4 }],
  "dot-notation": "error",
  "no-alert": "warn",
  yoda: ["warn", "never"],
  "max-lines": ["warn", { max: 300, skipComments: true }],
  "object-shorthand": ["error", "properties"],
  "max-statements": ["warn", { max: 20 }],
  "array-callback-return": ["warn", { checkForEach: true }],
};
